// This file was autogenerated by calcdeps.py
goog.addDependency("../r12a/deps.js", [], []);
goog.addDependency("../r12a/init.js", [], ['r12a.Person', 'r12a.ui.Input']);
goog.addDependency("../r12a/sample.js", ['r12a.Person'], []);
goog.addDependency("../r12a/ui/bar.js", ['r12a.ui.SlideBar'], ['goog.ui.Component']);
goog.addDependency("../r12a/ui/input.js", ['r12a.ui.Input'], ['goog.ui.LabelInput', 'r12a.ui.SlideBar']);
